"""
Reports Index — keeps a catalogue of every report the platform generates.

Governed by docs/013_Automation.md. Reports live in reports/ and are
committed to git (the durable archive — historical information must be
preserved, Project Vision invariant #6). This module regenerates
reports/INDEX.md so the whole track record is browsable in one place.

Usage:
    python src/cli/oil.py reports index
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[3]
REPORTS_DIR = _REPO_ROOT / "reports"
INDEX_PATH = REPORTS_DIR / "INDEX.md"


def _first_heading(md: str) -> str:
    for line in md.splitlines():
        line = line.strip()
        if line.startswith("#"):
            return line.lstrip("#").strip()
    return ""


def _summary_line(md: str) -> str:
    """First bold 'Bottom Line'-style line, else first non-heading text."""
    m = re.search(r"\*\*(BULLISH|BEARISH|NEUTRAL[^*]*|STRONG[^*]*)"
                  r".*?\*\*", md, re.IGNORECASE)
    if m:
        return m.group(0).strip("* ")
    for line in md.splitlines():
        s = line.strip()
        if s and not s.startswith("#") and not s.startswith("---"):
            return s[:120]
    return ""


def build_index() -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    reports = sorted(
        (p for p in REPORTS_DIR.glob("*.md") if p.name != "INDEX.md"),
        reverse=True)

    lines = [
        "# Kippa Reports Archive",
        "",
        f"_{len(reports)} report(s) · newest first · regenerated by "
        "`oil reports index`._",
        "",
        "| Date | Report | Read |",
        "|---|---|---|",
    ]
    for p in reports:
        md = p.read_text()
        title = _first_heading(md) or p.stem
        summary = _summary_line(md)
        label = title.replace("Kippa Oil Intelligence — ", "")
        lines.append(f"| `{p.stem}` | {label} — {summary} | [{p.name}]({p.name}) |")

    lines.append("")
    INDEX_PATH.write_text("\n".join(lines) + "\n")
    return INDEX_PATH


def main() -> None:
    path = build_index()
    n = sum(1 for p in REPORTS_DIR.glob("*.md") if p.name != "INDEX.md")
    print(f"✓ Indexed {n} report(s) → {path.relative_to(_REPO_ROOT)}")


if __name__ == "__main__":
    sys.exit(main())
